#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RentToGo_Assessment.Resource", IsApplication=true)]

namespace RentToGo_Assessment
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int address = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int btnlogin = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int btnregister = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int btnrgstration = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int createcustaddress = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int createcustname = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int createcustpassword = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int createcustphn = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int createcustusername = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int createusrname = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int lgnpassword = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int lgnusername = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int name = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int phnnumber = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int textView1 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int textView2 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int textView3 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int usrpswrd = 2130837521;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030002
			public const int activity_main = 2130903042;
			
			// aapt resource value: 0x7F030000
			public const int LoginPage = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Registration = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F040000
			public const int ic_launcher = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int ic_launcher_foreground = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int ic_launcher_round = 2130968578;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F050000
			public const int action_settings = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int app_name = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F060000
			public const int AppTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
